# fly.toml app configuration file generated for atticache on 2025-01-18T18:31:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atticache'
primary_region = 'hkg'

[build]
  image = 'registry.fly.io/atticache:latest'

[env]
  ATTIC_SERVER_DATABASE_URL = ''
  ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64 = ''
  AWS_ACCESS_KEY_ID = ''
  AWS_SECRET_ACCESS_KEY = ''

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-4x'
